apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1   # create 1 pod for the given templte below
  selector:
    matchLabels:
      component: web
  template:   #inside the templete we will list all the configuration of the pod which will be created by this deployment
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: stephengrider/multi-client
        ports: 
          - containerPort: 3000 